version: '3.4'
services:

  ag-collection:
    build:
      context: ./
      target: develop
    ports:
      - '4000:80'
    env_file: .env
    volumes:
      - /code/node_modules
      - ./:/code
    depends_on:
      - postgres
    command: yarn start

  # DATABASE
  postgres:
    image: postgres
    env_file: .env-pg
    ports:
      - 5434:5432


networks:
  default:
    driver: bridge
